# Generated by Django 2.1.4 on 2018-12-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_in', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'keyM',
                'verbose_name_plural': 'keyM',
            },
        ),
    ]
