# Generated by Django 2.1.4 on 2019-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=2)),
                ('device_name', models.CharField(max_length=20)),
                ('apiid', models.CharField(default='bl397233b7de02c055', max_length=18)),
                ('apikey', models.CharField(default='da5cbd210dbd9e994a9fdf5731aaae51', max_length=32)),
                ('expires_in', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'keyM',
                'verbose_name': 'keyM',
            },
        ),
    ]
