# Generated by Django 2.1.4 on 2018-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_stoken_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoken',
            name='expires_in',
            field=models.CharField(max_length=100),
        ),
    ]
