# Generated by Django 2.1.4 on 2019-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20181231_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoken',
            name='apiid',
            field=models.CharField(default='bl397233b7de02c055', max_length=18),
        ),
        migrations.AddField(
            model_name='stoken',
            name='apikey',
            field=models.CharField(default='da5cbd210dbd9e994a9fdf5731aaae51', max_length=32),
        ),
        migrations.AddField(
            model_name='stoken',
            name='device_name',
            field=models.CharField(default=models.CharField(max_length=2), max_length=20),
        ),
    ]
